### ISSUE TITLE
a question about vistool

### ISSUE THREAD

**Issue by Hollow-cat** [uglide/RocketPilot#11]
Hello！When I used the command “rocketpilot-vis”,it said cannot import name "InlineKeyboardMarkup" from "pyrogram".I don't konw how to reslove this problem.Also I was wondering if there is a more detailed documentation about this project rocketpilot.

**Comment by Hollow-cat** [comment]
I  guess is that I used the false version of module pykeyboard beacuse it uses  “from pygrogram import InlineKeyboardMarkup” in init.py. But I use the version 0.1.1+ of pykeyboard it said "cannot import name 'Pykeyboard' from 'pykeyboard'".

**Comment by uglide** [comment]
Hello @Hollow-cat Try to use my forked version of PyUserInput https://github.com/uglide/PyUserInput
