### ISSUE TITLE
cannot load library qttestability

### ISSUE THREAD

**Issue by Hollow-cat** [uglide/RocketPilot#12]
Hi uglide. I am sorry to bother you. I have followed your README file and built the rocketpilot and its driver.
When I used the command `rocketpilot-vis appname`,it said that  `Library qttestability load failed:"Cannot load library qttestability:(no such file or directory)`. Sure I do something when I build the qt application?
I am a new user of qt so I wonder if I have missed some steps in building this project.
Thank you for your attention.

**Comment by Hollow-cat** [comment]
Oh，I have copyed the libqttestability.so to my dir of qt lib and then the problem was resloved.I wonder that if I should copy all the shared object files in driver?

**Comment by uglide** [comment]
@Hollow-cat It's a possible solution. Alternatively, you can just use OS-specific env variables like `LD_LIBRARY_PATH`

**Comment by Hollow-cat** [comment]
I am grateful to you for your advice.
I think I should learn more basical knowledge about Linux and Qt.

**Comment by Hollow-cat** [comment]
I am grateful to you for your advice.
I think I should learn more basical knowledge about Linux and Qt.

**Comment by Hollow-cat** [comment]
I am grateful to you for your advice.
I think I should learn more basical knowledge about Linux and Qt.
